config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'pages#index'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name,
                                 :email,
                                 :password,
                                 :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name,
                                 :email,
                                 :password,
                                 :password_confirmation,
                                 :current_password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

require 'navigation_helper.rb'

module ApplicationHelper
  include NavigationHelper
end

app/helpers/navigation_helper.rb
# frozen_string_literal: true

module NavigationHelper
  def collapsible_links_partial_path
    if user_signed_in?
      'layouts/navigation/collapsible_elements/signed_in_links'
    else
      'layouts/navigation/collapsible_elements/non_signed_in_links'
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-fixed-top navbar-light">
  <div class="container">
    <!-- Elements visible all the time -->
    <div class="col-sm-7">
      <%= render 'layouts/navigation/header' %>
    </div><!-- col-sm-7 -->

    <!-- Elements collapses on smaller devices -->
    <div class="col-sm-5">
      <%= render 'layouts/navigation/collapsible_elements' %>
    </div><!-- col-sm-5 -->
  </div><!-- container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Collabfield</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/navigation' %>
  <%= yield %>
</body>

</html>

app/views/layouts/navigation/_collapsible_elements.html.erb
<!-- Collect the nav links, forms, and other content for toggling -->
<%# <div class="collapse navbar-collapse" id="collapsibleNavbar"> %>
<div class='collapse navbar-collapse' id="collapse_target">
  <ul class="navbar-nav">
    <%= render collapsible_links_partial_path %>
  </ul>
</div><!-- navbar-collapse -->

app/views/layouts/navigation/_header.html.erb
<div class='navbar-header'>
  <%= link_to  "CollabField", root_path, class:'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapse_target">
    <span class="navbar-toggler-icon"></span>
  </button>
</div>

app/views/layouts/navigation/collapsible_elements/_non_signed_in_links.html.erb
<li><%= link_to 'Login', login_path, class:"nav-item dropdown" %></li>
<li><%= link_to 'Signup', signup_path, class:"nav-item dropdown" %></li>

app/views/layouts/navigation/collapsible_elements/_signed_in_links.html.erb
<li class="nav-item dropdown dropdown-menu pc-menu">
  <a id="user-settings" class="nav-item dropdown nav-link dropdown-toggle" data-toggle="dropdown" data-target="dropdown-target" href="#">
    <span id="user-name" class="nav-item dropdown"><%= current_user.name %></span>
    <span class="caret"></span>
  </a>

  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdown_target">
    <li><%= link_to 'Edit Profile', edit_user_registration_path, class:'nav-item dropdown-item' %></li>
    <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, class:'nav-item dropdown-item' %></li>
  </ul>
</li>

<li class="nav-item dropdown mobile-menu">
  <%= link_to 'Edit Profile', edit_user_registration_path %>
</li>
<li class="nav-item dropdown mobile-menu">
  <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
</li>

app/views/pages/index.html.erb
<!DOCTYPE html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>CollabField HomePage</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  <h1>Home Page</h1>

</body>

</html>